project:
  type: website
  output-dir: docs

website:
  title: "INAB In-House Analysis"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Data & Metadata
        href: qmd/data_cleaning.qmd
      - text: Data Analytics
        href: qmd/data_analytics.qmd
      - text: Unix Commands
        href: qmd/unix.qmd